### ISSUE TITLE
mol_assem_report varies with each run

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#27]
It seems there is some indeterministic behaviour w.r.t the mol_assem_test:

```git diff
diff --git a/mol_assem_test.approved.txt b/mol_assem_test.approved.txt
index aaeeed8..6fdcda4 100644
--- a/mol_assem_test.approved.txt
+++ b/mol_assem_test.approved.txt
@@ -1,8 +1,8 @@
 Created empty molecule named Test.
 Added a carbon atom. Its location is [0.000000,0.000000,0.000000].
 Added another carbon atom. Its location is [0.000000,1.540000,-0.000000].
-Added an oxygen atom. Its location is [-0.565498,2.016666,-1.223888].
-Internal collisions: 0.417545 cu.A.
+Added an oxygen atom. Its location is [-1.215392,2.016667,0.583532].
+Internal collisions: 0.0106636 cu.A.
 Minimizing internal collisions...
-Internal collisions: 3.27826e-07 cu.A.
+Internal collisions: 6.14673e-08 cu.A.
 Saved test.sdf
```

This is a typical diff after running `make reports` (which regenerates all tests and overwrites the *.approved.txt files).

Is there some rand() calls hidden underneath here, or am I missing something?

**Comment by ssepeq** [comment]
This has to do with the central carbon atom's geometry, used for placing atoms around it. The first bonded atom (the "another carbon") is placed in the +Y direction. Subsequent atoms are placed at the tetrahedral angle (about 109 degrees) relative to the first one, but these exact locations are different each time and I've never figured out why.

Molecule::add_atom() calls Atom::get_next_free_geometry().

Atom::get_next_free_geometry() calls Atom::get_geometry_aligned_to_bonds().

Atom::get_geometry_aligned_to_bonds() calls align_points_3d().

align_points_3d() calls compute_normal() and find_3d_angle(), both of which are deterministic.

The differing values seem to hinge on align_points_3d() unpredictably selecting from a continuum of valid results when Atom::get_geometry_aligned_to_bonds() calculates "single aligned geometry", i.e. only one bonded atom exists to be able to ensure the return value is 109 deg from. Mathematically there should a way in this case to preferentially select one result from the continuum, e.g. the one closest to the +Z direction, but I can't think off the top of my head how to code that.

**Comment by ssepeq** [comment]
The differing internal collisions values are probably due to hydrogens.

**Comment by objarni** [comment]
Thanks for details, and especially the calls make. Found this spot, which looks suspicious:

```
        do
        {
            pt.x = 0.1 * (rand() % 503);  // rand() !!
            pt.y = 0.1 * (rand() % 503);
            pt.z = 0.1 * (rand() % 503);

            n = compute_normal(point, align, &pt);
            // cout << n.r << " ";
        }
        while (n.r < 0.01);
```

Notice the rand() calls. They will bring in indeterminism. It's in the align_points_3d method of Rotation.

**Comment by ssepeq** [comment]
Yup, I missed those.

**Comment by objarni** [comment]
From an automatic testing perspective, popular solutions are:

1. "scrub" the indeterministic data in tests. E.g. replace the float values with <VARIES>. This may be OK, depending on situation. It's not OK if the values are important for the behavour being tested.
2. Make the production code indeterministic.

I know too little to understand which situation this is.

**Comment by ssepeq** [comment]
I think it would be okay to remove the xyz coordinates from the output of mol_assem_test. I thought about replacing the one for the oxygen atom with an angle, i.e. just to make sure the C-C-O atoms form a 109deg angle. But even that could vary at a certain decimal place.

I've checked in a fix that makes align_points_3d() deterministic however.

**Comment by objarni** [comment]
Cool, tested it now, and there is less 'diffing'. However, still a little indeterminism, this time from time (heh):

```
    fprintf(os, "  podock-%02d%02d%02d%02d%02d%02d3D\n", gmtm->tm_year % 100, gmtm->tm_mon+1, gmtm->tm_mday,
            gmtm->tm_hour, gmtm->tm_min, gmtm->tm_sec
           );
```

This gives diffs like this:

```
git diff
diff --git a/mol_assem_test.approved.txt b/mol_assem_test.approved.txt
index 259d8e5..d678f07 100644
--- a/mol_assem_test.approved.txt
+++ b/mol_assem_test.approved.txt
@@ -8,7 +8,7 @@ Internal collisions: 3.8743e-07 cu.A.
 Saved test.sdf
 Content of test.sdf:
 Test
-  podock-2205300240543D
+  podock-2205300241213D
```

This is a typical "scrub output" situation, however since we are not using any approval library (only the 'hack' of creating text files via the makefile) I'm inclined to say 'can we make it indeterministic instead?'.

**Comment by ssepeq** [comment]
The line in the SDF output file is a datetime stamp.

**Comment by objarni** [comment]
Ah, I see! Is it important for the function of the SDF importers?

I think we could use 'sed' to clean/scrub the text data for the regression tests, I'll try it out for this issue!

BTW - I noticed you added the label 'invalid' to this issue. To me, this is a label put at an issue when it's a non-issue, and should not be fixed for that reason (miscommunication, bad idea, duplictate etc.). Was that your intention?

**Comment by ssepeq** [comment]
It's not. I believe it's normally a version number. Timestamp seemed to make sense in lieu of a version, I think the sed idea is a good approach.

The description for invalid just says "this doesn't seem right". Huh. I assumed it meant the program output doesn't seem right. That is really cryptic.

**Comment by ssepeq** [comment]
You're right about the label.

https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by ssepeq** [comment]
Is this still occurring?

**Comment by objarni** [comment]
Nope, closing. Good catch!
