### ISSUE TITLE
Where are file formats .sdf and .pdb described?

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#29]
When running podock tests', there are output files '.pdb' and '.sdf' created at various occasions.

Is there any documentation for these file formats? I couldn't find any browsing FAQ and some more pages on primaryodors.org.

(I did find the 3d visualization of a molecule though, really nice to see what this software is used for in the end!! :D )

**Comment by ssepeq** [comment]
Cool! 😊 (The graphics are certainly the best part!)

Both file formats are pretty standard in the computational chemistry world. PDB is the format of the [Protein Data Bank](https://www.rcsb.org/) and there's a description of it here: https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html

SDF is I guess some kind of wrapper for I think mol2, there's a description here: https://www.nonlinear.com/progenesis/sdf-studio/v0.9/faq/sdf-file-format-guidance.aspx

I'm not confident my code precidely follows either specification completely, only that the output is good enough for viewers like ngl and JSmol and that my classes can read other websites' files.

**Comment by ssepeq** [comment]
Added PDB and SDF as entries in the glossary.
