### ISSUE TITLE
Segfault in protest_report

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#38]
```
REPORT="protest.approved.txt"
./protest ARNDCEQGHILKMFPUSTWYV >"protest.approved.txt"
Segmentation fault (core dumped)
```
This is when invocing `make protest_report`.

It did work some day ago. The sequence run is more complicated than it used to be, perhaps this is why it is now crashing?

**Comment by ssepeq** [comment]
I forgot to note this. Proline and tryptophan are currently segfaulting and I haven't had a chance to look into it. So any sequence containing P or W will cause the crash. Thank you for catching this and opening an issue.

I think it's ideal that the test include all of the amino acids, that way if any of them are erroring (as we see here), the test will catch it. Unfortunately, protest has never fully worked and has always had problems giving incorrect output in specific circumstances.

**Comment by ssepeq** [comment]
If we are doing the 21 amino acids separately, then protein_test could just use a sequence like AAAAAAAAAA (polyalanine). Alanine is one of the least likely to fail and is the best one for alpha helices, and one of the output files that protein_test generates is an alpha helix.

**Comment by ssepeq** [comment]
Just know that the podock application itself generates .txt files as output, and we want to avoid checking those in. The viewer expects the .txt extension, but I guess we could change it to also accept something like .out or .dock and then have the podock.config output the new extension instead. Now that I think of it, the podock.config should have a comment explaining which extension(s) is/are compatible with the viewer.

**Comment by objarni** [comment]
I like the idea of a new kind of file extension for the output; it makes it very clear that it is a "podock file".  .dock or even .podock perhaps?

Then we could add that to the .gitignore file.

(Another solution would be to output in a "output/" folder, which could be .gitignore:d)

**Comment by ssepeq** [comment]
Hmmm, I think I like the .dock extension. The output folder is even better yet!

**Comment by objarni** [comment]
1. I have approved new versions the point and amino tests; I feel confident enough they are now working. Nice work getting all the amino tests to pass!!

2. The protein report doesn't segfailt anymore, cool! But it gives a big diff now. I'm not knowledgeable enough about the problem domain to know if it's ok to approve:

```
make protein_report
git diff
```

Would you look into approving it, or filing a bug if there is an issue? Maybe we need some more # filter (see molecule_report on how to do it)?

3. Aniso, molecule, mol_assem regression tests are passing. (no diff after running their respective report)

4. Atom test was missing an approval file (I hope that's the last of them heh!). Added.

**Comment by ssepeq** [comment]
Looking into protein report...

I notice all the reports ran when I did make all just now.

**Comment by ssepeq** [comment]
PR #44 will fix the protein report diff.

**Comment by ssepeq** [comment]
What was the molecule.cpp cout?

**Comment by objarni** [comment]
It was this line, which I added a # to for approval/regression/report's sake:

`cout << "# Ring closure anomaly " << anomaly << endl;`

**Comment by ssepeq** [comment]
Makes sense. Due to randomness.

Eventually we'll want a pass/fail on the ring anomaly as a test for #5, but that unfortunately is far from ready. The ring anomaly is basically a measure of how well the program was able to bend atoms into a loop while obeying their geometric rules. Their bonds should all be a certain length and a certain angle, and the closer the anomaly is to zero, the more accurate the simulated structure.

**Comment by ssepeq** [comment]
Seems to no longer be occurring.

The name of the target has changed since this issue was opened: `make protein_report`
