### ISSUE TITLE
mol_report indeterministic

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#39]
It seems every run of mol_report causes new output values:

![image](https://user-images.githubusercontent.com/68198/171487027-28262700-9585-4d12-a4be-c790a3167607.png)

Also, I'd like to rename the test to molecule_test as per convention in repo.

**Comment by ssepeq** [comment]
Yes to renaming it.

Hmmm, the output would be expected vary because this does a conformation calculation, therefore it contains randomness. Is there a way to write the test to accept a binding energy above a certain threshold? For example:

```
./mol_test 'CC(=O)[O-]' 'C[NH+](C)C'

Post-conformation intermol energy level: 6.89427 kJ/mol.
```
...where the test passes if the energy is > 5 kJ/mol?

(In a while I'll turn off the + and x chars in the output.)

**Comment by ssepeq** [comment]
Great idea outputting both!

[Ignore] makes me think the user should ignore it. :/ What if the marker were just a # followed by a space?

**Comment by objarni** [comment]
Yay! # it is!

**Comment by objarni** [comment]
OK, so I removed the .sdf output from the report, since it varied all the time and wasn't useful as regression test therefore.

I also introduced the filter lines beginning with `#` idea, see `molecule_report` target in makefile. (the rename happened too).

I had to modify `molecule.cpp`, since it was outputting lots of "x" in the report, and it was varying. I'm guessing it was some debug printout?

Also implemented the energyLevel SUCCESS/FAIL idea in `molecule_test.cpp` (no idea what a good energyLevelThreshold is, please modify to liking!).

With all that, I think this issue is closed.

**Comment by ssepeq** [comment]
energyLevelThreshold would depend on the molecules being tested. I've modified it to test acetic acid and trimethylamine with a 5 kJ/mol threshold. (Realistically I think it should be about 6-8 times that, not sure what's going on with the bindings.) The test is working great!
