### ISSUE TITLE
Root directory is getting crowded - ideas for subdirectories

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#40]
There are now almost 100 files in the root folder on my machine. I would like to move .approved.txt files to a subfolder "approved_files", as a start. There might be more sub folders that make sense, e.g. separating the 'basic code files' (point, atom etc) from the more application-level files (e.g podock) or the _test files.

Thoughts?

**Comment by ssepeq** [comment]
It would be a good idea to organize the files more. I haven't done so only out of laziness.

We could have a src folder and have the class files in a src/include or src/classes subfolder.

The various .o files could go in a bin folder. I'd rather keep the podock executable itself in the root folder unless there's a way to make it obvious where to find it. The _test executables could go into a test folder.

**Comment by objarni** [comment]
In general - in favor of all above.

Some small nitpicks:

  * bin/ is usually reserved for ... well binaries/executables. So .o would make more sense in an "obj/" or "objects/" folder
  * I'd like to have an "src/" folder just out of pure convention from other projects/languages; they could still build things into "test/" and "bin/" or even the root of the repo

Now that we have a somewhat robust automatic test suite (via the `make reports` command), these kind of re/structurings become a lot easier / more economic. So we shouldn't be afraid to try things out - it's always possible to change again.

**Comment by ssepeq** [comment]
Cool!

**Comment by objarni** [comment]
Wow what a cleanup!

I'm closing this issue for now, great work ☺️
