### ISSUE TITLE
make is rebuilding all of the targets every time.

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/podock#41]
Whenever I run make, it rebuilds everything, even if I didn't change any of the code.

**Comment by objarni** [comment]
Curios. And a point towards CMake: it generates a great makefile for us (with progress bars, possibility for parallell compilation etc.) and with a much cleaner / more declarative style of expression.

I am making progress on gcov / code coverage without CMake however, and our "regression system" is getting better by the day so I'm indecisive here.

What's your take on CMake vs makefile?

**Comment by ssepeq** [comment]
If it would still be possible to compile podock in environments where CMake is unavailable, then this sounds perfect!

**Comment by objarni** [comment]
In theory, it would - if we include Makefile that CMake would generate in the repository.

However, I would say it's not recommended, as CMake checks the system for compilers and other tooling, tweaking the generated Makefile to suit the system it is run in. Do you know the target systems' compiler etc.?

**Comment by ssepeq** [comment]
For the web host, here's the version info. It wouldn't be ideal to tie the makefile to a specific target environment, but it could be okay in the short term. The current makefile compiles perfectly.

```
$ make --version
GNU Make 4.2.1
Construit pour x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>
Ceci est un logiciel libre : vous êtes autorisé à le modifier et à la redistribuer.
Il ne comporte AUCUNE GARANTIE, dans la mesure de ce que permet la loi.
$ g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Part of my philosophy with podock arises from having been unable to compile AutoDock. As far as I could tell it can only be built with CMake which meant it would be unavailable on the remote server. Also my attempts to compile it locally (to add parameters that don't come with the software) were met with roadblocks. It worked out anyway since AutoDock doesn't do path based docking or break down its output by residue/by binding type, so it made sense to write my own. But with the intent that mine would be easy to build and easy to configure.

**Comment by ssepeq** [comment]
I don't have sudo access on the remote server.

The text file is a possible solution. $(OBJDIR) is part of all so that the first time a user builds the code, it will create the folders - a howto page on the internet said to do that. (I know, haha.) Another possibility would be a separate first time target that the user would have to make before they make all. Maybe there's a way to put a bash if statement to check if the dir already exists before calling mkdir?

**Comment by objarni** [comment]
Nice work on the makefile! `all` does not rebuild anymore, and from some random testing of e.g `touch src/classes/molecule.cpp` and the like, it does only rebuild what needs to be rebuilt!

Do you think we could close this, or any more concern?

**Comment by ssepeq** [comment]
Thank you! Yup, this one appears to be completed.
