### ISSUE TITLE
-fpermissive gives weird semantics

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#45]
I noticed the flag permissive is used in the makefile.

This means the compiler allows strange things like disregarding const qualifiers, basically invalidating the use of const at all (since you cannot trust the 'I won't change this state'-promise of const).

I'm working on removing the flag by adding / removing const in different places.

Note: You may see me use the syntax `char const *` order instead of `const char *`. This is known as the right-to-left-rule, and means you can actually read and understand the type better. The former is read (from right to left): "pointer to constant character", which is precisely what it is (the letter cannot be changed / is constant), while the latter, while meaning the same to the compiler/language, is utterly non-readable for a human. (you just have to know what it means through years of programming in C++).

(Semantically, const 'talks about what is left of it'. And then there is this weird exception, if there is nothing left of it, it talks about what is right of it! See e.g this thread on the topic of understanding complicated const type declarations https://stackoverflow.com/questions/7526152/easy-rule-to-read-complicated-const-declarations)

**Comment by objarni** [comment]
More on the right-to-left rule, seems like a really pedagocial explanation: https://linustechtips.com/blogs/entry/1573-const-pointers-references-and-right-to-left-reading/

**Comment by ssepeq** [comment]
Thank you tons for cleaning up the compiler warnings! -fpermissive is definitely a stopgap in the makefile and it will be great to remove that dependency. Gives better compatibility too.

I'll try to remember to put const after the type when defining a const pointer. The `const char*` syntax is just so familiar from a long time ago.

Good catch on get_atom_location!

**Comment by objarni** [comment]
I have now pushed the removal of `-fpermissive` CFLAG, as I'm not getting any "invalidates constness"-warnings/errors anymore. I hope it works for you too!

**Comment by ssepeq** [comment]
Works great! Thank you!
