### ISSUE TITLE
Switch public-only classes to structs.

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#48]
Classes and structs are semantically _very_ similar in C++, in fact, the only difference that I know of is that structs start with 'public:' implicitly, while classes start with 'private:' implicitly. This means that class declarations such as this:

```c++
class LocatedVector : public SCoord
{
	public:
	LocatedVector() { r = theta = phi = origin.x = origin.y = origin.z = 0; }
	LocatedVector(SCoord sc) { copy(sc); }
	void copy(SCoord sc) { r=sc.r; theta=sc.theta; phi=sc.phi; }
        Point origin;
};
```

.. can be simlified to this:

```c++
struct LocatedVector : public SCoord
{
	LocatedVector() { r = theta = phi = origin.x = origin.y = origin.z = 0; }
	LocatedVector(SCoord sc) { copy(sc); }
	void copy(SCoord sc) { r=sc.r; theta=sc.theta; phi=sc.phi; }
        Point origin;
};
```

**Comment by ssepeq** [comment]
Sure!

**Comment by objarni** [comment]
Feel free to pick any of these up!

Won't be able to code much next few days

**Comment by ssepeq** [comment]
No worries. Doing something leisurely/fun I hope? I might grab a few of these but am really wanting to get that metals utility working. I've got a cron on my local server that would do docking runs around the clock if only I could assemble good metalloprotein versions of all the olfactory receptors. :/
