### ISSUE TITLE
Unclear code, or potential bug in Molecule constructor

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#55]
This looks weird:

![image](https://user-images.githubusercontent.com/68198/172475115-6d7859ff-aa4c-4e75-9ddd-df9c0693fa29.png)

The first for-loop has no statement; it basically only counts up i until a nullptr value is found in collection. Is this a way to calculate the length of the array?

Written as a vector algorithm, and extracting the get-length logic to separate functin `arrayLength` it this would look like this instead:

```c++
    int i = arrayLength(collection);
    for (int j=0; j<i; j++)
        atoms.push_back(collection[j]);
```

**Comment by ssepeq** [comment]
It is to calculate the length of the array yes. There are a few of these in the code in various places, guess I could have made them clearer by using a more descriptive variable name and/or adding a comment that the semicolon after the loop is intentional.

**Comment by objarni** [comment]
Thanks! It is quite an ingenious way to use arrays, imagine it coming from C's null-terminated strings, just generalised to any type?

**Comment by ssepeq** [comment]
Why thank you! That was the inspiration, yeah. Can't rule out that I might have seen a similar usage back in the day, it's probably easy to tell my C++ chops are about 20 years out of date. 😀

**Comment by objarni** [comment]
C++ was my primary language around 2000-2005, then I got tired of it's intricacies and hurdles to do even simple things. However, I returned around 2016 since so called "modern C++" (starting with C++11) is a lot better. Except when it isn't hehe.

I do like C better than C++ in general, though, from an esthetic viewpoint. It's a more limited, more minimalistic language with more focus, and the property of being "learnable" within weeks instead of years (I'm still learning C++, 25 years after I started...).

**Comment by ssepeq** [comment]
Cool! It's great you've had that exposure to C++ and gotten to know the new features. My career drew me into coding in VB6 and then into PHP which is what my work has me using now.

C defintely has that nice simplicity. My other project on here is written in C, it's the control system for a Raspberry Pi UV camera. It's pretty amazing the things that can be written in just C.
