### ISSUE TITLE
Molecule::reallocate nulls all atoms

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#56]
```c++
void Molecule::reallocate()
{
    if (!(atcount % _def_atc))
    {
        int oac = atcount;
        int ac1 = oac + _def_atc;
        Atom** latoms = new Atom*[ac1+10];

        int i;
        if (!atoms.empty() && oac)
        {
            for (i=0; i<oac; i++) latoms[i] = atoms[i];
        }
        for (i=oac; i<ac1; i++) latoms[i] = nullptr;
        // delete[] atoms;
        atoms = latoms;
    }
    rotatable_bonds = nullptr;
}
```

The 3rd for-loop sets all items for latoms array (and _def_atc additional elements) to nullptr.

Then atoms is reassigned to latoms, which makes me think this is a bug? Reallocate "clears" all atoms by the looks of it ...

**Comment by objarni** [comment]
Oh, I see! Didn't spot the start-value in the 3rd loop. It is quite cryptic to read these algos'.

delete vs delete[] has been a cause for endless struggle for me too. The way I've understood it:

1. Anytime you allocate an array, use a corresponding delete[] to de-alloc.
2. If you use an array-of-pointers, first delete all objects using `delete` (a for loop)
3. ... then use `delete[]` on the array variable itself. BOTH are needed to release the mem

**Comment by ssepeq** [comment]
Except what about when deleting the array of pointers but not deleting the objects referenced by the pointers. That's the tricky part to have to figure out.

**Comment by objarni** [comment]
What is tricky about that case?

If you want to keep the objects (and not cause a memory leak), just copy the pointers before delete[]. If you don't want to keep them, delete them first, then the array itself.

**Comment by ssepeq** [comment]
Then delete[] won't delete the objects? It seemed like doing so was causing segfaults.

**Comment by objarni** [comment]
delete[] only frees up the memory allocated by the array, not what the array elements point to. It is not "smart" or "convenient".

So doing delete[] without deleting the objects, is a memory leak.

Segfault would be using the array after it has been deallocated, since the memory isn't the process's anymore. (it could also go well)
