### ISSUE TITLE
molecule_report varies

### ISSUE THREAD

**Issue by objarni** [primaryodors/podock#57]
There seems to be some variance left in molecule_report:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/68198/172545975-02b26e11-1537-421a-a752-aadf8430234e.png">

This means I cannot trust the molecule_test/report as a regression shield when refactoring molecule.cpp to vector (see #32 ).
 
I could just filter out the lines that cause variation, however I feel uncertain if the test is then still good enough (would catch regressions/refactoring mistakes) to protect me then? I'd rather fix the output to not be variable, as we did with an if FAIL/SUCCESS at some time.

**Comment by ssepeq** [comment]
Something is indeed failing. Internal clashes might report a large initial value like these but the code should "fix" the structure and report a second internal clashes value under 0.00001, which we can set a pass/fail threshold on.

The "molecule moved" line can be safely ignored.

**Comment by ssepeq** [comment]
This appears to be resolved. (Please feel free to reopen if not!)
