### ISSUE TITLE
Including test reports in default make?

### ISSUE THREAD

**Issue by ssepeq** [primaryodors/podock#64]
Currently the default `make all` target includes the tests and reports. Not long ago I added an option to `make code` that omits the test reports and just builds the executables.

If end users download the source to run it locally, without intending to make any changes to the code, would they want the tests to run at all? Especially given how some of the tests are currently failing.

The readme could be updated to instruct the user to `make code` instead of simply `make`. Or the default target could be changed to `code` rather than `all`, and the command to include reports would be explicitly `make all`.

Thoughts?

**Comment by objarni** [comment]
Why not fix the tests?

I prefer viewing make as a developer tool, and the tests are part of doing development.

For only building the podock binary, a make podock could be documented.

For even more convenience, a prebuilt podock binary could be made available on GitHub, is that seems to be valuable?

**Comment by ssepeq** [comment]
Eventually the problems with SMILES input will be fixed. I just don't have the math right or the algorithms or something. Most input strings work great, but the few that don't are the frustrating ones. I looked at the OpenBabel source and it builds rings from fragments, didn't delve too much because I don't want to copy their code, but it seems like a good approach.

I've gone ahead and created a `make podock` target in the makefile. Prebuilt binaries could be good! Maybe a strange question but would there have to be separate binaries for Linux and Mac? x86 and AMD? I'd like to also get podock compiling on Windows, only because some potential users might be limited to it by other software they're using.
