### ISSUE TITLE
Manually copy code from the-nightmare-version to the stable branch.

### ISSUE THREAD

**Issue by primaryodors** [primaryodors/podock#88]
After the docker became horribly broken due to untested code changes, a new branch called `stable` was split from the last-tested-good commit, and the head of the main branch was renamed `the-nightmare-version`.

Create a new branch for this issue, based off of `stable`. One by one, go through the additional features in `the-nightmare-version` and manually re-add/paste them into the codebase, **testing at each step**. Note the tests cannot be automated as they rely on identifying correct molecular behavior.

The following tests are required for this change. All of the below must pass before the code can be merged!

`test/molecule_test "NCCCC=O" "NCCCC=O"`
The two amine groups should hydrogen-bond to the two oxygens.

Cadaverine (protonated) in TAAR8:
The two amine groups should coordinate with ASP111 and ASP201. You will see binding energies of about -40 to -65 kJ/mol for each residue.

d-Limonene in OR1A1:
This is a known agonist and will fit in the binding pocket with little to no clashing and a total binding energy of at worst -5, more likely closer to -9.

Any code that prevents any of the tests from passing, must be omitted from the new branch.

Once the code passes **ALL OF THE TESTS**, create a PR.

**Comment by ssepeq** [comment]
List of nightmare commits:
https://github.com/primaryodors/podock/compare/stable...the-nightmare-version

**Comment by ssepeq** [comment]
[nightmare_tests.zip](https://github.com/primaryodors/podock/files/9136813/nightmare_tests.zip)

**Comment by ssepeq** [comment]
Test 3 usually fails but intermittently gives a good h-bond with ASN109 and a rather clashy pi-bond with TYR258. The code changes might do well to enhance the likelihood of this pose.

**Comment by ssepeq** [comment]
Currently, tests 1 and 3 are usually failing, while test 2 mostly succeeds.

🟥🟩🟥

**Comment by ssepeq** [comment]
🟩🟩🟥

**Comment by ssepeq** [comment]
🟩🟩🟥

**Comment by ssepeq** [comment]
🟩🟩🟥

**Comment by ssepeq** [comment]
Side chains are sometimes clashing with other parts of the protein outside the ligand + flexing residues logical grouping.

**Comment by ssepeq** [comment]
🟩🟩🟩

**Comment by ssepeq** [comment]
TAAR8 test took 468 seconds*; 1A1 test is taking similar. No PR until this number is under 180. Protein::get_residues_can_clash_ligand() is returning residues that are too far away to actually clash with the ligand, and the too-long residue list is slowing the calculation.

*Not 3 hours. Cat wanted attention and programmer wanted more sleep.

**Comment by ssepeq** [comment]
Test docks are now taking about 220 seconds. Too slow for the PR threshold but I'll take that over almost 500 any day.

**Comment by ssepeq** [comment]
> ~~No PR until this number is under 180.~~

@#$% that.

The local server is idly docking non-empirical pairs with failing code. It's time to get it going on some better code. 220 is not that much more than 180. I'm calling this version and creating the PR.
